name: Generate and Publish GitHub Contribution Grid

on:
  push:
    branches:
      - main  # Varsayılan ana dal adınızı kullanın

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Contribution Grid
        uses: Platane/snk@master
        with:
          github_user_name: alibaltaci  # GitHub kullanıcı adınızı kullanın

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/*  # dist dizini altındaki dosyaları ekleyin
          git commit -m "Update GitHub Contribution Grid"
          git push origin main  # Sadece "main" dala güncelleme yapın
