name: Generate and Publish GitHub Contribution Grid

on:
  push:
    branches:
      - main  # Varsayılan ana dal adınızı kullanın

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Contribution Grid
        uses: Platane/snk@master
        with:
          github_user_name: alibaltaci  # GitHub kullanıcı adınızı kullanın
         outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add dist/*  # dist dizini altındaki dosyaları ekleyin
          git commit -m "Update GitHub Contribution Grid"
          git push origin main  # Sadece "main" dala güncelleme yapın

                # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
